name: PR build check

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build_multisrc:
    name: Build multisrc modules
    needs: check_wrapper
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [all, en, ar, de, es, fr, id, it, ja, ko, pt, ru, th, tr, vi, zh, bg, hi, pl]
        # Full list of locales in project, but no APKs are produced for some of them here:
        # lang: [all, en, ar, ca, de, es, fr, id, it, ja, ko, pt, ru, th, tr, vi, zh, bg, hi, pl]
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Generate sources from the multi-source library
        uses: gradle/gradle-command-action@v2
        env:
          CI_MULTISRC: "true"
        with:
          arguments: :multisrc:generateExtensions
          cache-disabled: true

      - name: Build "${{ matrix.lang }}" extensions
        uses: gradle/gradle-command-action@v2
        env:
          CI_MULTISRC: "true"
          CI_MATRIX_LANG: ${{ matrix.lang }}
        with:
          arguments: assembleDebug
          cache-disabled: true

  build_individual:
    name: Build individual modules
    needs: check_wrapper
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [all, en, ar, ca, de, es, fr, id, it, ja, ko, pt, ru, th, tr, vi, zh]
        # Full list of locales in project, but no APKs are produced for some of them here:
        # lang: [all, en, ar, ca, de, es, fr, id, it, ja, ko, pt, ru, th, tr, vi, zh, bg, hi, pl]
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build "${{ matrix.lang }}" extensions
        uses: gradle/gradle-command-action@v2
        env:
          CI_MULTISRC: "false"
          CI_MATRIX_LANG: ${{ matrix.lang }}
        with:
          arguments: assembleDebug
          cache-disabled: true
